/**
 * PWA Compiler — generates manifest, service worker, and head tags
 * for Progressive Web App publishing.
 *
 * All functions are pure — no side effects, no store access.
 * Called by the publish pipeline after the page HTML is compiled.
 *
 * VAE Gap F additions:
 *   • generatePWAHeadTags now inlines the beforeinstallprompt deferral script
 *     so showInstallPrompt action step can trigger the native install dialog.
 *   • generateServiceWorker adds a proper offline fallback fetch handler.
 */

import type { PWAConfig, PWAIcon, PWAIconInput } from '../types/pwa.js';
import type { NexusVariable } from '../types/dataBind.js';

// ─── Manifest ────────────────────────────────────────────────────────────────

export function generateManifest(config: PWAConfig, pageUrl: string): string {
  const icons: PWAIcon[] = [];

  if (config.icon) {
    icons.push(
      { src: `${pageUrl}/icons/icon-192.png`, sizes: '192x192', type: 'image/png' },
      { src: `${pageUrl}/icons/icon-512.png`, sizes: '512x512', type: 'image/png' },
    );
  }

  const manifest = {
    name: config.appName,
    short_name: config.shortName,
    description: config.description,
    theme_color: config.themeColor,
    background_color: config.backgroundColor,
    display: config.display,
    start_url: config.startUrl || pageUrl,
    orientation: config.orientation,
    icons,
    ...(config.offlinePage ? { offline_page: config.offlinePage } : {}),
  };

  return JSON.stringify(manifest, null, 2);
}

// ─── Service Worker ───────────────────────────────────────────────────────────

export function generateServiceWorker(config: PWAConfig, assetUrls: string[]): string {
  const { cacheStrategy } = config;
  const staticAssets = JSON.stringify(assetUrls, null, 2);
  const offlinePage  = config.offlinePage ? JSON.stringify(config.offlinePage) : null;

  return `
// Nexus Architect — Generated Service Worker
// Do not edit this file manually.
const CACHE_NAME = 'nexus-v1';
const STATIC_ASSETS = ${staticAssets};
${offlinePage ? `const OFFLINE_PAGE = ${offlinePage};` : '// no offline page configured'}

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      const toCache = [...STATIC_ASSETS${offlinePage ? `, OFFLINE_PAGE` : ''}];
      return cache.addAll(toCache);
    })
  );
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k)))
    )
  );
  self.clients.claim();
});

self.addEventListener('fetch', (event) => {
  // Only handle same-origin GET requests
  if (event.request.method !== 'GET') return;

  const url = new URL(event.request.url);
  const isAPI    = url.pathname.startsWith('/api/') || url.pathname.startsWith('/wp-json/');
  const isImage  = /\\.(png|jpe?g|gif|svg|webp|avif)$/i.test(url.pathname);
  const isNav    = event.request.mode === 'navigate';

  if (isAPI) {
    // API: ${cacheStrategy.api}
    if ('${cacheStrategy.api}' === 'network-only') {
      return; // default browser fetch
    }
    event.respondWith(
      fetch(event.request).catch(() => caches.match(event.request))
    );
    return;
  }

  if (isImage) {
    // Images: ${cacheStrategy.images} — cache-first with network fallback
    event.respondWith(
      caches.match(event.request).then((cached) =>
        cached || fetch(event.request).then((res) => {
          const clone = res.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(event.request, clone));
          return res;
        })
      )
    );
    return;
  }

  // Pages: ${cacheStrategy.pages}
  if ('${cacheStrategy.pages}' === 'cache-first') {
    event.respondWith(
      caches.match(event.request).then((cached) => cached || fetch(event.request).catch(() => {
        ${offlinePage ? `if (isNav) return caches.match(OFFLINE_PAGE);` : '// no offline fallback'}
        return new Response('Offline', { status: 503, statusText: 'Service Unavailable' });
      }))
    );
  } else if ('${cacheStrategy.pages}' === 'stale-while-revalidate') {
    event.respondWith(
      caches.open(CACHE_NAME).then((cache) =>
        cache.match(event.request).then((cached) => {
          const fetched = fetch(event.request).then((res) => {
            cache.put(event.request, res.clone());
            return res;
          }).catch(() => {
            ${offlinePage ? `if (isNav) return caches.match(OFFLINE_PAGE);` : '// no offline fallback'}
            return new Response('Offline', { status: 503 });
          });
          return cached || fetched;
        })
      )
    );
  } else {
    // network-first with offline fallback
    event.respondWith(
      fetch(event.request).catch(async () => {
        const cached = await caches.match(event.request);
        if (cached) return cached;
        ${offlinePage ? `if (isNav) { const off = await caches.match(OFFLINE_PAGE); if (off) return off; }` : '// no offline fallback'}
        return new Response('Offline', { status: 503 });
      })
    );
  }
});
`.trim();
}

// ─── Icon Set (async, uses canvas) ───────────────────────────────────────────

export async function generateIconSet(input: PWAIconInput): Promise<PWAIcon[]> {
  const sizes = [72, 96, 128, 144, 152, 192, 384, 512];
  const icons: PWAIcon[] = [];

  for (const size of sizes) {
    // Prefer OffscreenCanvas (Worker-safe) with fallback to document.createElement
    let canvas: OffscreenCanvas | HTMLCanvasElement;
    let ctx: OffscreenCanvasRenderingContext2D | CanvasRenderingContext2D | null;

    if (typeof OffscreenCanvas !== 'undefined') {
      canvas = new OffscreenCanvas(size, size);
      ctx = (canvas as OffscreenCanvas).getContext('2d') as OffscreenCanvasRenderingContext2D | null;
    } else {
      canvas = document.createElement('canvas');
      (canvas as HTMLCanvasElement).width  = size;
      (canvas as HTMLCanvasElement).height = size;
      ctx = (canvas as HTMLCanvasElement).getContext('2d');
    }

    if (!ctx) continue;

    // Fill background with rounded rect
    ctx.fillStyle = input.bgColor || '#0e1511';
    ctx.beginPath();
    if ('roundRect' in ctx) {
      (ctx as CanvasRenderingContext2D).roundRect(0, 0, size, size, size * 0.15);
    } else {
      (ctx as CanvasRenderingContext2D).rect(0, 0, size, size);
    }
    ctx.fill();

    // Draw source image
    const img = new Image();
    img.src = input.sourceDataUrl;
    await new Promise<void>((resolve) => {
      img.onload = () => {
        const padding = size * 0.15;
        ctx!.drawImage(img, padding, padding, size - padding * 2, size - padding * 2);
        resolve();
      };
      img.onerror = () => resolve();
    });

    let dataUrl: string;
    if (canvas instanceof OffscreenCanvas) {
      const blob = await (canvas as OffscreenCanvas).convertToBlob({ type: 'image/png' });
      dataUrl = await new Promise<string>((resolve) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve(reader.result as string);
        reader.readAsDataURL(blob);
      });
    } else {
      dataUrl = (canvas as HTMLCanvasElement).toDataURL('image/png');
    }

    icons.push({
      src: dataUrl,
      sizes: `${size}x${size}`,
      type: 'image/png',
    });
  }

  return icons;
}

// ─── Head Tags ────────────────────────────────────────────────────────────────

/**
 * generatePWAHeadTags — returns the full set of <head> tags needed for PWA support.
 *
 * Includes:
 *   • manifest link + theme-color meta
 *   • Apple mobile web app metas
 *   • Service worker registration script
 *   • beforeinstallprompt deferral script (captures event on window.__nexusDeferredPrompt
 *     so the NexusActionEngine showInstallPrompt step can trigger it later)
 */
export function generatePWAHeadTags(config: PWAConfig): string {
  if (!config.enabled) return '';

  return `
  <link rel="manifest" href="/manifest.json">
  <meta name="theme-color" content="${config.themeColor}">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="default">
  <meta name="apple-mobile-web-app-title" content="${config.shortName}">
  <script>
    // PWA: capture beforeinstallprompt for use by showInstallPrompt action step
    window.addEventListener('beforeinstallprompt', function(e) {
      e.preventDefault();
      window.__nexusDeferredPrompt = e;
    });
    // Register service worker
    if ('serviceWorker' in navigator) {
      window.addEventListener('load', function() {
        navigator.serviceWorker.register('/sw.js').catch(function() {});
      });
    }
  </script>`.trim();
}

// ─── Nexus State Script ───────────────────────────────────────────────────────

export function generateNexusStateScript(variables: NexusVariable[]): string {
  const defaultValues: Record<string, unknown> = {};
  for (const v of variables) {
    defaultValues[v.id] = v.defaultValue;
  }

  return `<script>window.__NEXUS_STATE__ = ${JSON.stringify({ variables, values: defaultValues })};</script>`;
}

// ─── compilePWA — aggregate PWA artifact output ───────────────────────────────

export interface PWACompileResult {
  /** Content of /manifest.json */
  manifest: string;
  /** Content of /sw.js */
  serviceWorker: string;
  /** Generated icon set (may be empty if no icon source) */
  icons: PWAIcon[];
  /** Head tags to inject into <head> */
  headTags: string;
}

export async function compilePWA(config: PWAConfig, pageUrl: string, assetUrls: string[]): Promise<PWACompileResult> {
  const manifest      = generateManifest(config, pageUrl);
  const serviceWorker = generateServiceWorker(config, assetUrls);
  const headTags      = generatePWAHeadTags(config);

  // Icon generation requires a source image
  let icons: PWAIcon[] = [];
  if (config.icon) {
    try {
      icons = await generateIconSet(config.icon);
    } catch {
      // Icon generation is best-effort
    }
  }

  return { manifest, serviceWorker, icons, headTags };
}
