/**
 * PreviewPage — Phase 6.2
 *
 * Blueprint requirement:
 *   "A 'Preview' action renders the current draft state in a new tab without
 *    publishing it. The preview uses the same renderer as the canvas —
 *    there is no separate PHP template path. The preview URL is shareable
 *    for stakeholder review."
 *
 * Architecture:
 *   The builder tab writes the current page JSON to localStorage under
 *   key 'nx-preview-draft' before opening this page. This tab reads it,
 *   hydrates the CanvasStore, and renders using the full NodeRenderer —
 *   the exact same component tree used in the canvas, but without any
 *   builder chrome (no TopBar, no panels, no selection overlays).
 *
 *   For the WordPress adapter (production), this would be a real PHP-served
 *   URL that reads from the static file cache instead.
 *
 * Security notes:
 *   - The page data comes from the same origin (same tab localStorage).
 *   - html-embed widget content is the user's own content.
 *   - No external scripts are loaded.
 */

import { useEffect, useState, useRef } from 'react';
import type { NexusPage } from '@nexus/core';
import { compilePage } from '@nexus/core';

import { PREVIEW_STORAGE_KEY } from '@/lib/preview-constants';


// ─── Inline compiled HTML renderer ───────────────────────────────────────────

/**
 * Renders the compiled static HTML in an iframe (sandboxed) so the page styles
 * don't bleed into the builder's own CSS. This is the "same renderer" in the
 * sense that the HTML is generated by the same compiler used at publish time —
 * it's just shown inline rather than saved to disk.
 */
function StaticHtmlPreview({ html }: { html: string }) {
  const iframeRef = useRef<HTMLIFrameElement>(null);

  useEffect(() => {
    const iframe = iframeRef.current;
    if (!iframe) return;

    // Write compiled HTML directly into the iframe document
    const doc = iframe.contentDocument ?? iframe.contentWindow?.document;
    if (doc) {
      doc.open();
      doc.write(html);
      doc.close();
    }
  }, [html]);

  return (
    <iframe
      ref={iframeRef}
      title="Nexus Architect — Page Preview"
      className="w-full h-full border-0"
      sandbox="allow-scripts allow-same-origin"
      style={{ display: 'block', width: '100%', height: '100%', border: 'none' }}
    />
  );
}

// ─── Loading state ────────────────────────────────────────────────────────────

function PreviewLoading() {
  return (
    <div
      style={{
        display:         'flex',
        alignItems:      'center',
        justifyContent:  'center',
        height:          '100vh',
        background:      '#0d0d0d',
        color:           '#888',
        fontFamily:      'system-ui, sans-serif',
        flexDirection:   'column',
        gap:             '12px',
      }}
    >
      <svg width="40" height="40" viewBox="0 0 26 26" fill="none" style={{ animation: 'spin 1.4s linear infinite' }}>
        <defs>
          <linearGradient id="pg" x1="0" y1="0" x2="26" y2="26" gradientUnits="userSpaceOnUse">
            <stop offset="0%" stopColor="#10b981" />
            <stop offset="100%" stopColor="#059669" />
          </linearGradient>
        </defs>
        <rect width="26" height="26" rx="6" fill="url(#pg)" opacity="0.85" />
        <path d="M7 19V7H9.6L16.4 15.4V7H19V19H16.4L9.6 10.6V19H7Z" fill="white" />
      </svg>
      <span style={{ fontSize: '13px' }}>Rendering preview…</span>
      <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>
    </div>
  );
}

// ─── Error state ──────────────────────────────────────────────────────────────

function PreviewError({ message }: { message: string }) {
  return (
    <div
      style={{
        display:        'flex',
        alignItems:     'center',
        justifyContent: 'center',
        height:         '100vh',
        background:     '#0d0d0d',
        color:          '#f87171',
        fontFamily:     'system-ui, sans-serif',
        flexDirection:  'column',
        gap:            '8px',
        padding:        '32px',
        textAlign:      'center',
      }}
    >
      <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <circle cx="12" cy="12" r="10" /><line x1="12" y1="8" x2="12" y2="12" /><line x1="12" y1="16" x2="12.01" y2="16" />
      </svg>
      <p style={{ fontSize: '14px', fontWeight: 600 }}>Preview unavailable</p>
      <p style={{ fontSize: '12px', color: '#6b7280', maxWidth: '360px' }}>{message}</p>
      <button
        onClick={() => window.close()}
        style={{
          marginTop:    '16px',
          padding:      '8px 20px',
          background:   '#1f2937',
          border:       '1px solid #374151',
          borderRadius: '8px',
          color:        '#e5e7eb',
          cursor:       'pointer',
          fontSize:     '13px',
        }}
      >
        Close tab
      </button>
    </div>
  );
}

// ─── Preview toolbar (floating) ───────────────────────────────────────────────

function PreviewToolbar({
  page,
  sizeKb,
  onClose,
}: {
  page: NexusPage;
  sizeKb: number;
  onClose: () => void;
}) {
  const [visible, setVisible] = useState(true);

  // Auto-hide after 3 seconds of no mouse movement
  useEffect(() => {
    let timer: ReturnType<typeof setTimeout>;
    const show = () => {
      setVisible(true);
      clearTimeout(timer);
      timer = setTimeout(() => setVisible(false), 3000);
    };
    show();
    window.addEventListener('mousemove', show);
    return () => {
      window.removeEventListener('mousemove', show);
      clearTimeout(timer);
    };
  }, []);

  return (
    <div
      style={{
        position:     'fixed',
        top:          '16px',
        left:         '50%',
        transform:    'translateX(-50%)',
        zIndex:       9999,
        display:      'flex',
        alignItems:   'center',
        gap:          '12px',
        padding:      '8px 16px',
        background:   'rgba(13,13,13,0.92)',
        border:       '1px solid rgba(255,255,255,0.1)',
        borderRadius: '40px',
        backdropFilter: 'blur(12px)',
        boxShadow:    '0 4px 24px rgba(0,0,0,0.5)',
        transition:   'opacity 0.3s',
        opacity:      visible ? 1 : 0,
        pointerEvents: visible ? 'auto' : 'none',
        fontFamily:   'system-ui, sans-serif',
        fontSize:     '12px',
        color:        '#9ca3af',
        whiteSpace:   'nowrap',
      }}
    >
      {/* Logo mark */}
      <div style={{ width: 20, height: 20, borderRadius: 5, background: '#10b981', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
        <svg width="12" height="12" viewBox="0 0 16 16" fill="none">
          <path d="M3 13V3H5.2L10.8 9.8V3H13V13H10.8L5.2 6.2V13H3Z" fill="white" />
        </svg>
      </div>

      <span style={{ color: '#e5e7eb', fontWeight: 600 }}>{page.title}</span>

      <span style={{ color: '#4b5563' }}>|</span>

      <span>Draft preview</span>

      <span style={{ color: '#4b5563' }}>|</span>

      <span
        style={{
          padding:      '2px 8px',
          background:   'rgba(16,185,129,0.15)',
          border:       '1px solid rgba(16,185,129,0.3)',
          borderRadius: '12px',
          color:        '#10b981',
          fontSize:     '11px',
          fontWeight:   600,
        }}
      >
        {sizeKb.toFixed(1)} KB
      </span>

      <button
        onClick={onClose}
        style={{
          marginLeft:   '4px',
          padding:      '4px 12px',
          background:   'rgba(255,255,255,0.07)',
          border:       '1px solid rgba(255,255,255,0.1)',
          borderRadius: '20px',
          color:        '#9ca3af',
          cursor:       'pointer',
          fontSize:     '12px',
          transition:   'background 0.15s',
        }}
        onMouseEnter={(e) => { e.currentTarget.style.background = 'rgba(255,255,255,0.12)'; }}
        onMouseLeave={(e) => { e.currentTarget.style.background = 'rgba(255,255,255,0.07)'; }}
      >
        ✕ Close
      </button>
    </div>
  );
}

// ─── Main PreviewPage ─────────────────────────────────────────────────────────

export default function PreviewPage() {
  const [html,       setHtml]       = useState<string | null>(null);
  const [page,       setPage]       = useState<NexusPage | null>(null);
  const [sizeKb,     setSizeKb]     = useState(0);
  const [error,      setError]      = useState<string | null>(null);
  const [loading,    setLoading]    = useState(true);

  useEffect(() => {
    // Read page data from localStorage (written by TopBar before window.open)
    try {
      const raw = localStorage.getItem(PREVIEW_STORAGE_KEY);
      if (!raw) {
        setError(
          'No preview data found. Open the preview from the builder by clicking the Preview button.',
        );
        setLoading(false);
        return;
      }

      const pageData = JSON.parse(raw) as NexusPage;

      // Compile to static HTML using the same compiler as publish
      const result = compilePage(pageData);

      setPage(pageData);
      setHtml(result.html);
      setSizeKb(result.sizeKb);
      setLoading(false);
    } catch (err) {
      console.error('[PreviewPage] Failed to compile preview:', err);
      setError(
        err instanceof Error
          ? `Compilation error: ${err.message}`
          : 'Failed to compile preview. Check the browser console for details.',
      );
      setLoading(false);
    }
  }, []);

  if (loading) return <PreviewLoading />;
  if (error)   return <PreviewError message={error} />;
  if (!html || !page) return <PreviewError message="No content to preview." />;

  return (
    <div style={{ width: '100vw', height: '100vh', overflow: 'hidden', background: '#fff' }}>
      <PreviewToolbar
        page={page}
        sizeKb={sizeKb}
        onClose={() => window.close()}
      />
      <StaticHtmlPreview html={html} />
    </div>
  );
}

// Export the storage key so TopBar can use it without hardcoding
// Re-exported from lib/preview-constants for backward compat
